services:
  arangoproxy:
    container_name: arangoproxy
    image: arangoproxy
    depends_on:
      - "arangodb"
    build:
      context: .
      target: arangoproxy
    networks:
      docs_net:
        ipv4_address: 192.168.129.4
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./migration-tools:/home

  site:
    container_name: site
    image: site
    depends_on:
      - "arangoproxy"
    build:
      context: .
      target: hugo
    ports:
      - "1313:1313"
    networks:
      docs_net:
        ipv4_address: 192.168.129.3
    volumes:
      - ./site:/site
    
  arangodb:
    container_name: arangodb
    image: arangodb/enterprise:latest
    ports:
      - "8520:8529"
    networks:
      docs_net:
        ipv4_address: 192.168.129.5
    environment:
      - ARANGO_NO_AUTH=1
    
  # arango_3_9:
  #   container_name: arango_maintainer
  #   image: arangodb:3.9
  #   build:
  #     context: .
  #     target: arango_maintainer
  #   networks:
  #     docs_net:
  #       ipv4_address: 192.168.129.10

  # arango_maintainer:
  #   container_name: arango_maintainer
  #   image: arango_maintainer
  #   build:
  #     context: .
  #     target: arango_maintainer
  #   networks:
  #     docs_net:
  #       ipv4_address: 192.168.129.10
  

networks:
  docs_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.129.0/24
          gateway: 192.168.129.1

