baseURL: "http://example.org/"
languageCode: "en-us"
title: "ArangoDB Documentation"
theme: "hugo-theme-relearn"
timeout: "200000000"

menu:
  shortcuts:
    - name: "<i class='fab fa-fw fa-github'></i> GitHub repo"
      identifier: "ds"
      url: "https://github.com/ArangoDB/ArangoDB/issues"
      weight: 10
    
markup:
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2

  highlight:
    style: "emacs"

  goldmark:
    renderer:
      unsafe: true

outputs:
  home: ["HTML", "RSS", "JSON"]

caches:
  assets:
    dir: :resourceDir/_gen
    maxAge: 0
  getcsv:
    dir: :cacheDir/:project
    maxAge: 0
  getjson:
    dir: :cacheDir/:project
    maxAge: 0
  getresource:
    dir: :cacheDir/:project
    maxAge: 0
  images:
    dir: :resourceDir/_gen
    maxAge: 0
  modules:
    dir: :cacheDir/modules
    maxAge: 0

params:
  failOnBrokenLinks: false
  failOnBrokenExamples: false 
  useCodeblockHook: true
  buildForApiDocs: false
  
  pygmentsUseClassic: false
  description: "Documentation for ArangoDB"
  showVisitedLinks: true
  alwaysopen: false
  collapsibleMenu: true
  disableBreadcrumb: false
  disableNextPrev: false
  disableLandingPageButton: true
  titleSeparator: "::"
  themeVariant: [ "relearn-light", "relearn-dark", "learn", "neon", "blue", "green", "red" ]
  disableSeoHiddenPages: true
  additionalContentLanguage: [ "en" ]
  custom_css: ["css/*"]
  swaggerInitialize: "{ \"theme\": \"light\" }"


